### ISSUE TITLE
Make global variables available in the repl?

### ISSUE THREAD

**Issue by joelmukuthu** [skerit/janeway#10]
Hi, is it possible to make global variables in a file run with `janeway file.js` available in the REPL, similar to what https://www.npmjs.com/package/node-repl#example does?

And thanks for the awesome work!

**Comment by skerit** [comment]
Oh sorry, didn't see this new issue 'till now. I think it should be possible, let me check!

**Comment by skerit** [comment]
Ah, spoke a bit too soon :)

`node-repl` actually runs the required code BEFORE its own code in the same module wrapper function.

I can't do that for multiple reasons. I need Janeway code to run first, and I use `vm` to execute the REPL input.

I could run the required code in the same `vm` context, but if I don't wrap the required code in a function, things like `return` in the module would not work, and if I do then new variables will get scoped anyway.

**Comment by joelmukuthu** [comment]
Your suggestion sounds like it would work! I think janeway would be a cool tool for creating interactive demos, but in most cases one needs to set up the demo environment hence this feature request. Let me know if I can help!

**Comment by skerit** [comment]
Ok, I could add it as a startup option and/or user configuration to do it this way, if that's good enough for you :)

**Comment by joelmukuthu** [comment]
Startup option as in CLI flag? That would be wonderful :)
