### ISSUE TITLE
Remove usage of ProtoBlast

### ISSUE THREAD

**Issue by piranna** [skerit/janeway#5]
I'm trying to follow how the module works to be able to extend it but the usage of ProtoBlast make it confusing by not following standard Node.js idioms (seems more like Java, isn't it?). I propose to remove it and use standard prototype inheritance and similar functionality. What do you think?

**Comment by skerit** [comment]
It's quite easy actually, the big problem is that there is no documentation for it yet.

And anyway, you can just extend the classes the "normal" way. All the `setMethod` calls are easy helper methods to set the given function on the classes' prototype.

**Comment by piranna** [comment]
Why not just set them directly? Just curious... I was willing to add some of the features of https://github.com/jonathanslenders/ptpython/ but I don't knlw where to start (and I must to admit I'm not sure if blessed current architecture is capable to do it...).

**Comment by skerit** [comment]
I'll gladly answer your curious questions ;)

First of all: Protoblast is a library I've also written. You can compare it to Sugar.js and underscore, with a few extra's added to it, and built for performance (sugar & underscore are mainly built for the browser, it's fast enough for that, but on a node server you really want to squeeze every ms out of your code)

I once started a documentation website, but it's far from finished. I've just recently started my freelance career and it's keeping me mighty busy.

To answer this specific question: the classes-part of Protoblast is built to keep my code "DRY" (as in "don't repeat yourself").

One way of defining a class would be like so:

	function MyClass() {
		this.myMethod = function myMethod() {
			// method code
		};
	}

But defining methods like this is wildly inefficient. Every new instance has to create the method functions, methods are enumerable, ... The only positive thing here is that these methods can have "private" variables.

Another way is like this:

	function MyClass() {}

	MyClass.prototype.myMethod = function myMethod() {
		// method code
	};

That's what I used to do, and this is fine (and still possible with Protoblast).
The main downside is that methods will still be enumerable, and you really should not have enumerable properties in your prototype.

So the good way to define a method would be this:

    function MyClass() {}

	Object.defineProperty(MyClass.prototype, 'myMethod', {
		enumerable: false,
		configurable: false,
		writable: false,
		value: function myMethod() {
			// method code
		}
	});

That's great, but it's *a lot* of code to repeat, don't you think?
The `Object.defineProperty` you have to call each time, the `MyClass.prototype` you'll always have to pass along, the `'myMethod'` name you have to give (even though the function has the same name), and all the property flags of course.

Oh, and about the function name: I make it a point to name all my functions. I don't like anonymous functions, and this way it's easier to fix errors.

Anyway, so using the Protoblast code all you have to do is:

    var MyClass = Function.inherits(function MyClass() {});

	MyClass.setMethod(function myMethod() {
		// method code
	});

`setMethod` basically does what the `Object.defineProperty` code above does, but with a few extras (like if this class is inheriting another class that has the same method, that old method will now be set as a property of the new method under `super`)

It allows me to write code very quickly, developing it gave me lots of insights into the working of JavaScript and prototypal inheritance, and I think it's way better than the new Class syntax.

Anyhoo... That's a really nice idea, the ptpython bit. It's definitely something I wanted to add.

**Comment by piranna** [comment]
This needs to be written somewhere... :-P


> I once started a documentation website, but it's far from finished. I've just recently started my freelance career and it's keeping me mighty busy.

I've just started as a freelances one month ago and don't have almost time for my projects too :-(


> The main downside is that methods will still be enumerable, and you really should not have enumerable properties in your prototype.

Well, maybe it's a personal question, I've never seen this statement before... I could understand why you think it, but I don't think is too much a problem, and I only set them as not enumerable when I want to hide them because it's a "protected" API (for private ones I set them directly inside the constructor, although it consume more memory). Also, I've read recently an article that claimed (with stats) that when using not enumerable properties access performance (and that include methods lookup) got decreaed 5 times compared to having them enumerable (both by direct access or by using `Object.defineProperty()`), so I think it doesn't really compensate...


> That's great, but it's a lot of code to repeat, don't you think?

Yeah, definitely it's too much ;-)


> Oh, and about the function name: I make it a point to name all my functions. I don't like anonymous functions, and this way it's easier to fix errors.

I don't remember the "priviledged" methods (the ones defined inside the constructor), but the "public" ones (defined on the prototype) get automatically its name from the prototype attribute where they are set if they don't have one, so they are not anonimous any more :-)


> var MyClass = Function.inherits(function MyClass() {});
> 
> MyClass.setMethod(function myMethod() {
>     // method code
> });
> 
> setMethod basically does what the Object.defineProperty code above does, but with a few extras (like if this class is inheriting another class that has the same method, that old method will now be set as a property of the new method under super)

I honestly don't see anything that can't be done with prototype inheritance and the `utils` module... :-( I understand your point, but if it's just a matter of setting the methods not enumerable on the prototype, I would define them on a plain object and use a function to tuneup it and assign on the prototype with `Prototype.defineProperties()`. Also the `Function.inherits` method seems extrange to me, I would use it on another module instead of extending Function. At API level it would be:

```javascript
function MyClass() {}

setMethods(MyClass, {
  myMethod: function() {
    // method code
  }
})
```

It's mostly the same, but I find it more clear to read and understand.

> It allows me to write code very quickly, developing it gave me lots of insights into the working of JavaScript and prototypal inheritance, and I think it's way better than the new Class syntax.

Problem with ES6 classes is that they are ugly because they are inspired by Java and there's no clear limits on the method definitions, and seems there's too much magic there. If at least It would be used the `function` keyword to define the methods... :-/


> Anyhoo... That's a really nice idea, the ptpython bit. It's definitely something I wanted to add.

Well, I'm happy you liked it :-) Another cool terminal is [TermKit](https://github.com/unconed/TermKit), I would love to have the tick on the left to show when the command was succesful or a clock while it's running, and show the commands output in a subterminal instead of keep scrolling the console so you can have several commands running at the same time on the same session. I'm planning to use this on NodeOS, so you can suppose why I'm willing to exec commands on this... ;-)

**Comment by skerit** [comment]
I'll take a look, thanks for the suggestions!
