### ISSUE TITLE
Show brackets on objects

### ISSUE THREAD

**Issue by piranna** [skerit/janeway#7]
The example demo show that objects content is shown directly, I think it would be good to show also some aesthetic brackets to know better when they start and end.

**Comment by skerit** [comment]
Ok, as a test I've added simple {} or [] brackets. Was that what you had in mind?

**Comment by piranna** [comment]
Exactly, at least in the short term :-P In the long term, ideally it would
be cool that object and arrays could be expanded recursively the same way
as Chrome Dev Console does :-D Unluclily I don't know if blessed is
poserful enough... :-(

**Comment by skerit** [comment]
Well, you can click open nested objects. Is that not working for you? 

If not: try scrolling a bit first. (scroll can get buggy at times)

**Comment by piranna** [comment]
I must to admit that I have not tested janeway yet... I wanted to use it as basis for a shell on NodeOS but it was difficult. Now that I've splitted it and started to build a real shell I can be able to use janeway as an improved repl, so I hope to be able to test it soon :-)

**Comment by skerit** [comment]
Oh, that's interesting! I've seen nodeos popup here and there, looks promising.

And Blessed shouldn't have any problem with those things, btw.

It just paints what Janeway tells it too, and Janeway only gets object properties when you actually click on them. So yeah, much like those devtools.

**Comment by piranna** [comment]
> Oh, that's interesting! I've seen nodeos popup here and there, looks
promising.

Well, pull-requests are welcome ;-)

> And Blessed shouldn't have any problem with those things, btw.
>
> It just paints what Janeway tells it too, and Janeway only gets object
properties when you actually click on them. So yeah, much like those
devtools.

I love blessed, but has some important architecture flaws, too much
baremetal for my taste and don't easily allow some advanced things that
could be done with double buffer or stacked layers. I'm too much used to
html layouts... :-P

**Comment by skerit** [comment]
I see you got involved in the blessed-ng fork, but it too seems quite dead right now?

**Comment by piranna** [comment]
> I see you got involved in the blessed-ng fork, but it too seems quite dead right now?

Sort of... too much busy with work and other projects, and there's too much work to do on `blessed-ng` to refactor it that I'm not sure if it compensate the effort. I would like to go for it someday, by the moment I've removed the widgets and keeps to clean it a bit more before moving to double buffering and later reassemble it again, but code has several bad design decisions that complicate to do this :-/
