### ISSUE TITLE
dotfile for user defined styles and such?

### ISSUE THREAD

**Issue by MrRacoon** [skerit/janeway#8]
Very cool project.

I was curious what you think about loading some dotfile like `~/.janeway` which could contain configurables, such as style menu colors and alternate prompt string.

**Comment by skerit** [comment]
Sure, sounds like a good idea!

I'd like to make more things customizable, right now everything is mostly set to my needs. Anything in particular you require?

**Comment by MrRacoon** [comment]
Colors are cool. But I'd love to be able to expand the max number of suggestions in the autocompletion list.

**Comment by skerit** [comment]
Well it took a while, but most styles can now be set in a `~/.janeway/janeway.json` config file.

I also added a persistent cli history, something I was seriously missing.

Haven't published it to NPM yet, though.

**Comment by skerit** [comment]
v0.2.3 has been released
